# This workflow runs the latest CodeQL CLI and checks against CodeQL's Cpp library.
# This is the source for the GitHub Security Code Scanning job.

name: "CodeQL Analysis"

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
    
  # Allow manual scheduling
  workflow_dispatch:

jobs:
  analyze:
    name: Analysis
    runs-on: windows-2025-vs2026
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: c-cpp
          build-mode: manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          submodules: 'recursive'
      - name: Install Nuget Packages
        run: nuget restore .\packages.config -PackagesDirectory .\packages\
      - name: Get changed files
        id: get-changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          separator: ","
      - name: Initialize CodeQL
        uses: github/codeql-action/init@c4dd10e44af883a891fe31ced449bcb4a6728b9b # v3.37.6
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          config-file: microsoft/Windows-Driver-Developer-Supplemental-Tools/config/codeql-config.yml@development
      - if: github.event_name == 'pull_request'
        run: |
          $changedFiles = "${{ steps.get-changed-files.outputs.all_changed_files }}".Split(',')
          .\.github\scripts\Build-ChangedSamples.ps1 -ChangedFiles $changedFiles -Verbose
        env: 
          WDS_Configuration: Debug
          WDS_Platform: x64
          WDS_WipeOutputs: ${{ true }}
      - if: github.event_name == 'push'
        run: .\Build-Samples.ps1 -Verbose -ThrottleLimit 1
        env:
          WDS_Configuration: Debug
          WDS_Platform: x64
          WDS_WipeOutputs: ${{ true }}
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@c4dd10e44af883a891fe31ced449bcb4a6728b9b # v3.37.6
        with:
          category: "/language:${{matrix.language}}"
